spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/main_db
    username: ignacio
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: rescue_me_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ignacio
    password: 12345678
    listener:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 5
        multiplier: 2.0
    template:
      mandatory: true

  flyway:
    enabled: true
    schemas: rescue_me_schema
    locations: classpath:db/migration

  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379

jwt:
  secret: 23e586808ea364607079ec5b830ba702e80680339864b175eb2f5a13abd214e7

cors:
  allowed-origins:
    - http://localhost:4200/
    - http://rescue_me_app:4200/

rabbit:
  exchange:
    auth: authApi.exchange
  queue:
    user-register-command: authApi.userRegisterCommand.queue
    user-register-reply: authApi.userRegisterReply.queue
    compensate-user-register-command: authApi.userRegisterCompensateCommand.queue
  routing-key:
    user-register-command: authApi.userRegisterCommand.routingKey
    user-register-reply: authApi.userRegisterReply.routingKey
    compensate-user-register-command: authApi.userRegisterCompensateCommand.routingKey

servlet:
  multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 10MB

logging:
  level:
    org:
      springframework:
        security: DEBUG
