spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        default_schema: rescue_me_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    template:
      mandatory: true

  flyway:
    enabled: true
    schemas: rescue_me_schema
    locations: classpath:db/migration

  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST_NAME}
      port: ${REDIS_HOST_PORT}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

rabbit:
  exchange:
    auth: authApi.exchange
  queue:
    initiate-user-registration-command: authApi.initiateUserRegistrationCommand.queue
    rollback-user-registration-command: authApi.rollbackUserRegistrationCommand.queue
    confirm-user-registration-command: authApi.confirmUserRegistrationCommand.queue
    failure-user-registration-reply: authApi.failureUserRegistrationReply.queue
    success-user-registration-reply: authApi.successUserRegistrationReply.queue
  routing-key:
    initiate-user-registration-command: authApi.initiateUserRegistrationCommand.routingKey
    rollback-user-registration-command: authApi.rollbackUserRegistrationCommand.routingKey
    confirm-user-registration-command: authApi.confirmUserRegistrationCommand.routingKey
    failure-user-registration-reply: authApi.failureUserRegistrationReply.routingKey
    success-user-registration-reply: authApi.successUserRegistrationReply.routingKey
