spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        default_schema: rescue_me_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 5
        multiplier: 2.0
    template:
      mandatory: true

  flyway:
    enabled: true
    schemas: rescue_me_schema
    locations: classpath:db/migration

  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST_NAME}
      port: ${REDIS_HOST_PORT}

jwt:
  secret: ${JWT_SECRET}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

rabbit:
  exchange:
    auth: authApi.exchange
  queue:
    user-register-command: authApi.userRegisterCommand.queue
    user-register-reply: authApi.userRegisterReply.queue
    compensate-user-register-command: authApi.userRegisterCompensateCommand.queue
  routing-key:
    user-register-command: authApi.userRegisterCommand.routingKey
    user-register-reply: authApi.userRegisterReply.routingKey
    compensate-user-register-command: authApi.userRegisterCompensateCommand.routingKey

servlet:
  multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 10MB