spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    test:
      database:
        replace: any
logging:
  level:
    org:
      springframework:
        security: DEBUG